import type { SalesDetailReportColumnKey } from '@/types'

export const COLUMN_LABELS: Record<SalesDetailReportColumnKey, string> = {
  orderNumber: 'Número de Pedido',
  orderId: 'ID Pedido',
  createdAt: 'Fecha / Hora',
  orderStatus: 'Estado Pedido',
  locationName: 'Local',
  organizationName: 'Organización',
  customerName: 'Cliente',
  customerPhone: 'Teléfono Cliente',
  customerEmail: 'Email Cliente',
  cashierName: 'Cajero / Operador',
  productName: 'Producto',
  sku: 'Código SKU',
  categoryName: 'Categoría',
  quantity: 'Cantidad',
  unitPrice: 'Precio Unitario',
  subtotal: 'Subtotal Línea',
  discountName: 'Nombre Descuento',
  discountType: 'Tipo Descuento',
  discountValueType: 'Modalidad Descuento',
  discountPercent: '% Descuento',
  discountAmount: 'Monto Descuento',
  creditUsed: 'Crédito Aplicado',
  paymentMethod: 'Método de Pago',
  paymentStatus: 'Estado Pago',
  grossAmount: 'Monto Bruto Pedido',
  orderDiscount: 'Descuento Total Pedido',
  totalPaid: 'Monto Neto Pagado',
  voidStatus: 'Estado Anulación / Devolución',
  voidQuantity: 'Cant. Anulada',
  voidAmount: 'Monto Anulado',
  voidReason: 'Motivo Anulación',
  voidUser: 'Usuario Creador Anulación',
  voidAuthorizer: 'Autorizador Anulación (Admin)',
}

export const DEFAULT_VISIBLE_COLUMNS: SalesDetailReportColumnKey[] = [
  'createdAt',
  'orderNumber',
  'customerName',
  'cashierName',
  'productName',
  'quantity',
  'unitPrice',
  'subtotal',
  'discountAmount',
  'totalPaid',
  'paymentMethod',
  'voidStatus',
]
