import type {
  Ingredient,
  InventoryItem,
  InventoryItemWithIngredient,
  StockMovement,
  CreateStockMovementInput,
  PaginationParams,
} from '@/types'

/**
 * Repository contract for the Inventory module.
 *
 * Phase note: These models are defined in the schema but the service layer
 * is not yet active. This interface defines the contract for when
 * InventoryService is implemented.
 */
export interface IInventoryRepository {
  // ── Ingredients ─────────────────────────────────────────────────────────

  /**
   * Find an ingredient by ID.
   * Returns null if not found or soft-deleted.
   */
  findIngredientById(id: string): Promise<Ingredient | null>

  /**
   * List all active ingredients for an organization.
   */
  findIngredientsByOrganizationId(
    organizationId: string,
    options?: PaginationParams
  ): Promise<Ingredient[]>

  // ── Inventory Items ──────────────────────────────────────────────────────

  /**
   * Get the inventory item for a specific ingredient at a specific location.
   * Returns null if no stock record exists yet.
   */
  findItemByLocationAndIngredient(
    locationId: string,
    ingredientId: string
  ): Promise<InventoryItem | null>

  /**
   * List all inventory items for a location with ingredient details.
   */
  findItemsByLocationId(locationId: string): Promise<InventoryItemWithIngredient[]>

  /**
   * List inventory items that are at or below their minimum quantity threshold.
   * Used for low-stock alerts.
   */
  findLowStockByLocationId(locationId: string): Promise<InventoryItemWithIngredient[]>

  // ── Stock Movements ──────────────────────────────────────────────────────

  /**
   * Record a stock movement (purchase, sale, waste, etc.).
   * Atomically updates InventoryItem.quantity by the delta.
   * Positive delta = inbound. Negative delta = outbound.
   */
  recordMovement(data: CreateStockMovementInput): Promise<StockMovement>

  /**
   * List stock movements for an inventory item (audit trail).
   */
  findMovementsByItemId(
    inventoryItemId: string,
    options?: PaginationParams
  ): Promise<StockMovement[]>

  /**
   * List stock movements generated by a specific order.
   */
  findMovementsByOrderId(orderId: string): Promise<StockMovement[]>
}
